language: haskell

install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod +x ~/.local/bin/stack

script:
  - stack setup --no-terminal
  - stack build --fast --no-terminal
  - stack haddock --no-haddock-deps

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $PROJECT_ROOT/.stack-work/dist/5c8418a7/doc/html/studienarbeit-flagchecker
  github_token: $GITHUB_TOKEN
  on:
    branch: master

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true
