name:                studienarbeit-flagchecker
version:             0.1.0.0
github:              "githubuser/studienarbeit-flagchecker"
license:             BSD3
author:              "Leon Kladnik"
maintainer:          "lkladnik@hm.edu"
copyright:           "2017 Leon Kladnik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Manages files and simplifies renaming large numbers.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/studienarbeit-flagchecker#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  studienarbeit-flagchecker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - studienarbeit-flagchecker

tests:
  studienarbeit-flagchecker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - studienarbeit-flagchecker
